#!/usr/bin/env python3
"""
Create a portable sandbox bundle for a CITL bot and optionally create/pull models.

This script is designed for demo handoff into:
- Docker
- Kubernetes (Job manifest)
- Slurm (batch script)
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Iterable, List


DEFAULT_REQUIRED_MODELS = [
    "olmo2:13b",
    "olmo2:7b",
    "olmo-3:7b-instruct",
    "olmo-3:7b-think",
    "nomic-embed-text:latest",
]


def _run(cmd: List[str], check: bool = True, capture: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        check=check,
        text=True,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.STDOUT if capture else None,
    )


def _has_model(installed: Iterable[str], requested: str) -> bool:
    req = (requested or "").strip()
    if not req:
        return False
    got = {m.strip() for m in installed if m.strip()}
    if req in got:
        return True
    if ":" not in req and f"{req}:latest" in got:
        return True
    if req.endswith(":latest") and req.split(":", 1)[0] in got:
        return True
    return False


def _list_installed_models() -> List[str]:
    cp = _run(["ollama", "list"])
    models: List[str] = []
    for line in (cp.stdout or "").splitlines():
        ln = line.strip()
        if not ln or ln.lower().startswith("name"):
            continue
        models.append(ln.split()[0].strip())
    return sorted(set(models), key=str.lower)


def _sanitize_model_name(raw: str) -> str:
    name = re.sub(r"[^a-zA-Z0-9_.:-]+", "-", (raw or "").strip()).strip("-")
    return name or "citl-demo-bot"


def _write_text(path: Path, text: str, executable: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    if executable:
        path.chmod(path.stat().st_mode | 0o111)


def _build_modelfile_text(base_model: str, system_prompt: str, bot_name: str, color: str, lang: str) -> str:
    return (
        f"# CITL-BOTNAME: {bot_name}\n"
        f"# CITL-COLOR: {color}\n"
        f"# CITL-LANG: {lang}\n"
        f"# CITL-DESC: generated by hive_off_bot_cli.py\n"
        f"FROM {base_model}\n"
        f'SYSTEM """\n{system_prompt.strip()}\n"""\n'
    )


def main() -> int:
    ap = argparse.ArgumentParser(description="Create a sandbox demo bundle for a CITL bot.")
    ap.add_argument("--model-name", required=True, help="Target custom model name (e.g., citl-demo-bot-v1)")
    ap.add_argument("--base-model", default="olmo2:13b", help="Base model for Modelfile FROM")
    ap.add_argument("--bot-name", default="CITL Demo Bot", help="Metadata bot name")
    ap.add_argument("--citl-color", default="soft_midnight", help="Metadata color key")
    ap.add_argument("--citl-lang", default="en", help="Metadata language code")
    ap.add_argument("--system-prompt-file", default="", help="Path to SYSTEM prompt text file")
    ap.add_argument(
        "--system-prompt",
        default=(
            "You are CITL Assistant, a reliable educational support bot. "
            "Use only verified local context and avoid speculation."
        ),
        help="SYSTEM prompt text (used if --system-prompt-file is not provided)",
    )
    ap.add_argument("--outdir", default="", help="Output bundle directory")
    ap.add_argument(
        "--required-model",
        action="append",
        default=[],
        help="Extra model to preflight (repeatable).",
    )
    ap.add_argument("--pull-missing", action="store_true", help="Pull missing required models")
    ap.add_argument("--create-custom", action="store_true", help="Run 'ollama create' for the target model")
    ap.add_argument("--write-modelfile", action="store_true", help="Write Modelfile into output bundle")
    ap.add_argument(
        "--demo-prompt",
        default="Explain in 5 bullet points why local-first classroom AI improves privacy governance.",
        help="Prompt text used by demo scripts",
    )
    args = ap.parse_args()

    if shutil.which("ollama") is None:
        print("ERROR: ollama command not found in PATH.", file=sys.stderr)
        return 2

    model_name = _sanitize_model_name(args.model_name)
    base_model = (args.base_model or "").strip() or "olmo2:13b"

    outdir = Path(args.outdir).expanduser() if args.outdir else Path("data") / "sandbox_bots" / model_name.replace(":", "-")
    outdir = outdir.resolve()
    outdir.mkdir(parents=True, exist_ok=True)

    if args.system_prompt_file:
        sp_path = Path(args.system_prompt_file).expanduser().resolve()
        if not sp_path.exists():
            print(f"ERROR: system prompt file not found: {sp_path}", file=sys.stderr)
            return 2
        system_prompt = sp_path.read_text(encoding="utf-8", errors="ignore").strip()
    else:
        system_prompt = (args.system_prompt or "").strip()

    if not system_prompt:
        print("ERROR: system prompt is empty.", file=sys.stderr)
        return 2

    required = list(DEFAULT_REQUIRED_MODELS)
    required.extend(args.required_model or [])
    if base_model not in required:
        required.insert(0, base_model)

    installed = _list_installed_models()
    missing = [m for m in required if not _has_model(installed, m)]

    print(f"[INFO] Output directory: {outdir}")
    print(f"[INFO] Installed models: {len(installed)}")
    if missing:
        print("[WARN] Missing models:")
        for m in missing:
            print(f"  - {m}")
    else:
        print("[OK] Required models already installed.")

    if missing and args.pull_missing:
        for m in missing:
            print(f"[PULL] {m}")
            _run(["ollama", "pull", m], check=True, capture=False)
        installed = _list_installed_models()
        missing = [m for m in required if not _has_model(installed, m)]

    if missing:
        print("[WARN] Continuing with missing models. Bundle is still generated.")

    modelfile_path = outdir / f"Modelfile.{model_name}"
    if args.write_modelfile or args.create_custom:
        modelfile = _build_modelfile_text(
            base_model=base_model,
            system_prompt=system_prompt,
            bot_name=args.bot_name,
            color=args.citl_color,
            lang=args.citl_lang,
        )
        _write_text(modelfile_path, modelfile)
        print(f"[OK] Wrote Modelfile: {modelfile_path}")

    if args.create_custom:
        if not modelfile_path.exists():
            print("ERROR: cannot create custom model without Modelfile.", file=sys.stderr)
            return 2
        print(f"[CREATE] ollama create {model_name} -f {modelfile_path}")
        _run(["ollama", "create", model_name, "-f", str(modelfile_path)], check=True, capture=False)
        print(f"[OK] Created/updated model: {model_name}")

    demo_prompt_path = outdir / "demo_prompt.txt"
    _write_text(demo_prompt_path, args.demo_prompt.strip() + "\n")

    run_demo_py = outdir / "run_demo.py"
    _write_text(
        run_demo_py,
        f"""#!/usr/bin/env python3
import json
import os
import sys
from pathlib import Path
from urllib.request import Request, urlopen

host = (os.environ.get("OLLAMA_HOST") or "http://127.0.0.1:11434").rstrip("/")
model = (os.environ.get("OLLAMA_MODEL") or "{model_name}").strip()
prompt_file = Path(os.environ.get("PROMPT_FILE") or "{demo_prompt_path.name}")
prompt = os.environ.get("PROMPT")
if not prompt:
    prompt = prompt_file.read_text(encoding="utf-8", errors="ignore").strip()

payload = {{"model": model, "prompt": prompt, "stream": False}}
req = Request(
    host + "/api/generate",
    data=json.dumps(payload).encode("utf-8"),
    headers={{"Content-Type": "application/json"}},
    method="POST",
)
with urlopen(req, timeout=300) as r:
    data = json.loads(r.read().decode("utf-8", errors="ignore"))
print((data.get("response") or "").strip())
""",
        executable=True,
    )

    run_demo_sh = outdir / "run_demo.sh"
    _write_text(
        run_demo_sh,
        f"""#!/usr/bin/env bash
set -euo pipefail
DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
export OLLAMA_HOST="${{OLLAMA_HOST:-http://127.0.0.1:11434}}"
export OLLAMA_MODEL="${{OLLAMA_MODEL:-{model_name}}}"
export PROMPT_FILE="${{PROMPT_FILE:-$DIR/{demo_prompt_path.name}}}"
python3 "$DIR/run_demo.py"
""",
        executable=True,
    )

    dockerfile = outdir / "Dockerfile"
    _write_text(
        dockerfile,
        f"""FROM python:3.11-slim
WORKDIR /app
COPY run_demo.py /app/run_demo.py
COPY run_demo.sh /app/run_demo.sh
COPY {demo_prompt_path.name} /app/{demo_prompt_path.name}
RUN chmod +x /app/run_demo.sh /app/run_demo.py
ENV OLLAMA_HOST=http://host.docker.internal:11434
ENV OLLAMA_MODEL={model_name}
CMD ["/app/run_demo.sh"]
""",
    )

    k8s_job = outdir / "k8s-job.yaml"
    _write_text(
        k8s_job,
        f"""apiVersion: batch/v1
kind: Job
metadata:
  name: {model_name.replace(':', '-').replace('_', '-').lower()}-demo
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: bot-demo
        image: citl/{model_name.replace(':', '-').lower()}-demo:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: OLLAMA_HOST
          value: "http://ollama.ollama.svc.cluster.local:11434"
        - name: OLLAMA_MODEL
          value: "{model_name}"
""",
    )

    slurm_job = outdir / "slurm-job.sh"
    _write_text(
        slurm_job,
        f"""#!/usr/bin/env bash
#SBATCH --job-name={model_name.replace(':', '-')[:30]}
#SBATCH --output=slurm-%j.out
set -euo pipefail
DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
export OLLAMA_HOST="${{OLLAMA_HOST:-http://127.0.0.1:11434}}"
export OLLAMA_MODEL="${{OLLAMA_MODEL:-{model_name}}}"
python3 "$DIR/run_demo.py"
""",
        executable=True,
    )

    readme = outdir / "README.md"
    _write_text(
        readme,
        f"""# CITL Bot Sandbox Bundle

Model name: `{model_name}`
Base model: `{base_model}`

## Local demo
```bash
./run_demo.sh
```

## Docker demo
```bash
docker build -t citl/{model_name.replace(':', '-').lower()}-demo:latest .
docker run --rm \\
  -e OLLAMA_HOST=http://host.docker.internal:11434 \\
  -e OLLAMA_MODEL={model_name} \\
  citl/{model_name.replace(':', '-').lower()}-demo:latest
```

## Kubernetes demo
1. Build/push the Docker image to your registry.
2. Update `k8s-job.yaml` image reference if needed.
3. Run:
```bash
kubectl apply -f k8s-job.yaml
kubectl logs -l job-name={model_name.replace(':', '-').replace('_', '-').lower()}-demo --tail=100
```

## Slurm demo
```bash
sbatch slurm-job.sh
```

## Provenance checks
```bash
ollama list
ollama show {model_name}:latest
```
""",
    )

    summary = {
        "model_name": model_name,
        "base_model": base_model,
        "outdir": str(outdir),
        "missing_models": missing,
        "modelfile": str(modelfile_path) if modelfile_path.exists() else "",
    }
    _write_text(outdir / "bundle_summary.json", json.dumps(summary, indent=2) + "\n")

    print("\n[OK] Sandbox bundle generated:")
    for name in [
        modelfile_path.name if modelfile_path.exists() else None,
        "run_demo.py",
        "run_demo.sh",
        "Dockerfile",
        "k8s-job.yaml",
        "slurm-job.sh",
        "README.md",
        "bundle_summary.json",
    ]:
        if not name:
            continue
        print(f"  - {outdir / name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

